/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ServiceItem } from "./components/gcds-srvinfo/gcds-srvinfo";
export { ServiceItem } from "./components/gcds-srvinfo/gcds-srvinfo";
export namespace Components {
    /**
     * The Service and Information component provides links to commonly used services and information.
     */
    interface GcdsSrvinfo {
        /**
          * Apply banding background to the section
          * @default false
         */
        "banded": boolean;
        /**
          * Number of columns for desktop layout (1 or 3)
          * @default true
         */
        "columns": boolean;
        /**
          * Whether to show the heading
          * @default false
         */
        "headingVisible": boolean;
        /**
          * Number of service items to display (1-9)
          * @default 9
         */
        "items": number;
        /**
          * Array of service items with linkText, linkHref, and description. Accepts an array of objects or a JSON string.
          * @default '[]'
         */
        "serviceItems": Array<ServiceItem> | string;
    }
}
declare global {
    /**
     * The Service and Information component provides links to commonly used services and information.
     */
    interface HTMLGcdsSrvinfoElement extends Components.GcdsSrvinfo, HTMLStencilElement {
    }
    var HTMLGcdsSrvinfoElement: {
        prototype: HTMLGcdsSrvinfoElement;
        new (): HTMLGcdsSrvinfoElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-srvinfo": HTMLGcdsSrvinfoElement;
    }
}
declare namespace LocalJSX {
    /**
     * The Service and Information component provides links to commonly used services and information.
     */
    interface GcdsSrvinfo {
        /**
          * Apply banding background to the section
          * @default false
         */
        "banded"?: boolean;
        /**
          * Number of columns for desktop layout (1 or 3)
          * @default true
         */
        "columns"?: boolean;
        /**
          * Whether to show the heading
          * @default false
         */
        "headingVisible"?: boolean;
        /**
          * Number of service items to display (1-9)
          * @default 9
         */
        "items"?: number;
        /**
          * Array of service items with linkText, linkHref, and description. Accepts an array of objects or a JSON string.
          * @default '[]'
         */
        "serviceItems"?: Array<ServiceItem> | string;
    }
    interface IntrinsicElements {
        "gcds-srvinfo": GcdsSrvinfo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The Service and Information component provides links to commonly used services and information.
             */
            "gcds-srvinfo": LocalJSX.GcdsSrvinfo & JSXBase.HTMLAttributes<HTMLGcdsSrvinfoElement>;
        }
    }
}
